### ISSUE TITLE
Getting stuck inside a vehicle / no control over the vehicle

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#413]
When a player enters a vehicle on the driver side and then shuffels the seat over to the passenger seat, the next player entering the vehicle on the driver side won't have any control over the vehicle (can't accelerate, can't steer and sometimes can't even exit the vehicle resulting being stuck in it)!
This is pretty much game-breaking in a lot of situations.

## Steps to Reproduce
This can be easily reproduced with the native "**taskShuffleToNextVehicleSeat**":

1. **Player A** enters the vehicle as driver
2. **Player A** calls native to shuffle to the passenger seat:
`game.taskShuffleToNextVehicleSeat(alt.Player.local.scriptID, alt.Player.local.vehicle.scriptID, 0);`
3. **Player B** enters the vehicle as a driver and can't properly interact with it

This probably happens because the server still thinks **Player A** is the syncer of the vehicle.

**Comment by FabianTerhorst** [comment]
Same as #292 but i don't close it because of the reproducing steps.

**Comment by FabianTerhorst** [comment]
Test again with beta build #1012 @Hardy535  @Lekenthun @tastydev

**Comment by Lekenthu** [comment]
Okaaaaay. I'll check it out in the evening.

**Comment by vadzz-dev** [comment]
This one should be fixed but #292 is something different

**Comment by Hardy535** [comment]
It's not 100% fixed. The way I described it on my first post is fixed but I found another way of getting stuck inside of a vehicle.
I'm not always able to reproduce the bug but this is the best approach could find:
1. **Player A** enters the vehicle as driver
2. **Player A** calls native to shuffle to the passenger seat:
`game.taskShuffleToNextVehicleSeat(alt.Player.local.scriptID, alt.Player.local.vehicle.scriptID, 0);`
3. **Player B** enters the vehicle as driver
4. **Player B** exits the vehicle as driver
5. **Player A** shuffles back to the driver seat via native:
`game.taskShuffleToNextVehicleSeat(alt.Player.local.scriptID, alt.Player.local.vehicle.scriptID, 0);`
6. **Player A** can't exit the vehicle _(can be workarounded by Player B entering the vehicle as passenger, then Player A can exit the vehicle)_

**Comment by tastydev** [comment]
Can confirm it is still happening, the stuck is over if the previously "driver"(bug origin?) leaves the server

**Comment by Lhoerion** [comment]
> Can confirm it is still happening, the stuck is over if the previously "driver"(bug origin?) leaves the server

Can't confirm that, tried it on #1025

> It's not 100% fixed. The way I described it on my first post is fixed but I found another way of getting stuck inside of a vehicle.
> I'm not always able to reproduce the bug but this is the best approach I could find:
> 
>     1. **Player A** enters the vehicle as driver
> 
>     2. **Player A** calls native to shuffle to the passenger seat:
>        `game.taskShuffleToNextVehicleSeat(alt.Player.local.scriptID, alt.Player.local.vehicle.scriptID, 0);`
> 
>     3. **Player B** enters the vehicle as driver
> 
>     4. **Player B** exits the vehicle as driver
> 
>     5. **Player A** shuffles back to the driver seat via native:
>        `game.taskShuffleToNextVehicleSeat(alt.Player.local.scriptID, alt.Player.local.vehicle.scriptID, 0);`
> 
>     6. **Player A** can't exit the vehicle _(can be workarounded by Player B entering the vehicle as passenger, then Player A can exit the vehicle)_

I managed to reproduce this everytime

**Comment by Lekenthu** [comment]
The problem reported by Hardy535 has not been resolved, but I think my issue is resolved.

**Comment by Hardy535** [comment]
I think my problem will result in your problem @Lekenthu and if this gets fixed yours is also fixed.
When you are stuck in the vehicle on the driver seat (just like I described), you can still exit the vehicle by changing to the passanger seat and then exiting the vehicle.
After that you often can't enter the vehicle on the driver-side anymore like in #292

**Comment by vadzz-dev** [comment]
I need you to check it on lates dev branch

**Comment by vadzz-dev** [comment]
@Hardy535 @tastydev I need you to test it on latest dev branch

**Comment by tastydev** [comment]
will look into it later today

**Comment by Hardy535** [comment]
Couldn't reproduce it so far, let's wait on an answer from @tastydev if he still can get this bug.

**Comment by tastydev** [comment]
same as @Hardy535 could not reproduce this anymore on dev branch
